### ISSUE TITLE
After Sign In I get an error and the moskool.com/courses page stays blank

### ISSUE THREAD

**Issue by hansschenker** [mo-sharif/mo-skool#2]
I sent you a picture of the errror - see below:
![moskool-error](https://user-images.githubusercontent.com/19405175/84588329-c7112000-ae26-11ea-82f5-cd2655b870b9.png)

**Comment by mo-sharif** [comment]
Hi Hans! That's a great catch!!
Just released a fix for that, and you should be able to see courses now
Thank you for your support :D
